innovit_profil:
    resource: "@InnovitProfilBundle/Resources/config/routing.yml"
    prefix:   /

innovit_general:
    resource: "@InnovitGeneralBundle/Resources/config/routing.yml"
    prefix:   /

# app/config/routing.yml

SdzBlogBundle:
    resource:  "@SdzBlogBundle/Resources/config/routing.yml"
    prefix:    /blog