<?php

namespace Proxies\__CG__\Innovit\ProfilBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Question extends \Innovit\ProfilBundle\Entity\Question implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'idCours', 'question', 'rep1', 'rep2', 'rep3', 'rep4', 'rep', 'explications');
        }

        return array('__isInitialized__', 'id', 'idCours', 'question', 'rep1', 'rep2', 'rep3', 'rep4', 'rep', 'explications');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Question $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCours($idCours)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCours', array($idCours));

        return parent::setIdCours($idCours);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCours()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCours', array());

        return parent::getIdCours();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuestion($question)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuestion', array($question));

        return parent::setQuestion($question);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuestion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuestion', array());

        return parent::getQuestion();
    }

    /**
     * {@inheritDoc}
     */
    public function setRep1($rep1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRep1', array($rep1));

        return parent::setRep1($rep1);
    }

    /**
     * {@inheritDoc}
     */
    public function getRep1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRep1', array());

        return parent::getRep1();
    }

    /**
     * {@inheritDoc}
     */
    public function setRep2($rep2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRep2', array($rep2));

        return parent::setRep2($rep2);
    }

    /**
     * {@inheritDoc}
     */
    public function getRep2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRep2', array());

        return parent::getRep2();
    }

    /**
     * {@inheritDoc}
     */
    public function setRep3($rep3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRep3', array($rep3));

        return parent::setRep3($rep3);
    }

    /**
     * {@inheritDoc}
     */
    public function getRep3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRep3', array());

        return parent::getRep3();
    }

    /**
     * {@inheritDoc}
     */
    public function setRep4($rep4)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRep4', array($rep4));

        return parent::setRep4($rep4);
    }

    /**
     * {@inheritDoc}
     */
    public function getRep4()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRep4', array());

        return parent::getRep4();
    }

    /**
     * {@inheritDoc}
     */
    public function setRep($rep)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRep', array($rep));

        return parent::setRep($rep);
    }

    /**
     * {@inheritDoc}
     */
    public function getRep()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRep', array());

        return parent::getRep();
    }

    /**
     * {@inheritDoc}
     */
    public function setExplications($explications)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExplications', array($explications));

        return parent::setExplications($explications);
    }

    /**
     * {@inheritDoc}
     */
    public function getExplications()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExplications', array());

        return parent::getExplications();
    }

}
