innovit_homepage:
    pattern:  /Accueil
    defaults: { _controller: InnovitGeneralBundle:General:Acceuil }
innovit_general_load:
    pattern:  /general/special/{page}
    defaults: { _controller: InnovitGeneralBundle:General:load }
innovit_redirection:
    pattern:  /general/redirection
    defaults: { _controller: InnovitGeneralBundle:General:redirection }
    