innovit_general_homepage:
    pattern:  /general/{name}
    defaults: { _controller: InnovitGeneralBundle:General:index }
    requirements:
        name: qsnous|flashactus|Accueil|liensutiles|login
innovit_redirection:
    pattern:  /general/redirection
    defaults: { _controller: InnovitGeneralBundle:General:redirection }
    